"""empty message

Revision ID: 41934667275e
Revises: a623fa2d6e14
Create Date: 2025-04-12 18:34:44.903610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41934667275e'
down_revision = 'a623fa2d6e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_college_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_constraint('uq_college_code', type_='unique')

    # ### end Alembic commands ###
